config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

Rails.application.routes.draw do

  get 'slideshows/channels'

  get 'slideshows/slideshow'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root "static_pages#home"

  devise_for :users, controllers: { registrations: "registrations" }

  match 'slideshows/update_slideshow',	to: 'slideshows#update_slideshow', 	via: 'post'
  match 'slideshows/update_slideshow',	to: 'slideshows#update_slideshow', 	via: 'get'
  match 'slideshows/', 					        to: 'static_pages#home', 			      via: 'get'
  match 'slideshows/home',              to: 'slideshows#home',              via: 'get'
  match 'slideshows/foo',               to: 'slideshows#foo',               via: 'post' 

  match '/info',                        to: 'static_pages#info',            via: 'get'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home

  end

  def info
      
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.haml
.row.hero-unit
    .tagline
        %h1 Welcome to DA Slideshows
        %p The art you love, the way it was meant to be experienced.
        -unless current_user
            %p#action!= "#{link_to("Sign in", new_user_session_path)} or #{link_to("Register", new_user_registration_path)} now to create your own custom slideshows!"
    .attribution{ style: "display : none;" }


-unless current_user
    .row#sub-action
        != "#{link_to("Sign in", new_user_session_path)} or #{link_to("Register", new_user_registration_path)} to get started!"

.row.instructions
    = image_tag("../images/howitworks1.jpg", class: "img-responsive pull-left col-sm-8 col-md-9", id: "how-it-works")    
    .sidebar.col-xs-12.col-sm-4.col-md-3
        %ul.pull-right
            %h2 How It Works
            %li!= "Open the #{link_to "Channel Changer", slideshows_channels_path, target: :_blank} on your mobile device, such as a phone or tablet."
            %li!= "Then open your #{link_to "Slideshow", slideshows_slideshow_path, target: :_blank} on a larger screen. (Internet Explorer on Xbox works great!)"
            %li!= "Tap to select a new image on your phone or tablet and the slideshow will instantly update to show you more art similar to the channel you selected! You can find more usage tips on our #{link_to "info page", info_path, target: :_blank}."

app/views/static_pages/info.html.haml
.info
    .container
        %h1 Usage tips
        -# %hr
        .row
            DA Slideshows was designed to be a novel way to find, share, and enjoy artwork tailored to your tastes. Displaying this art on large screens, with the ability to easily change the theme to fit your mood and style, is the main idea behind DA Slideshows. 
            %p
            DA Slideshows works best when used with two devices. Use a mobile device like a tablet or a phone for the Channel Changer, then display your Slideshow on a larger screen. 
            %p
            Here's a few ideas to get you started:

            %ul
                %li Game consoles such as the Xbox and Playstation have web browser apps. Log in and use them to display your Slideshow.
                %li Televisions such as Samsung's Smart TV have built-in web browsers. These can be used for the Slideshow as well.
                %li If you have a desktop computer you can run the slideshow on your monitor. If you have a second monitor, you can run the slideshow on one screen and work on the other!
                %li AppleTV allows you to mirror your Mac's computer screen to your TV. Open your Slideshow on your computer and mirror it to your Apple TV.
                %li With Google's Chromecast, you can cast the content of your Google Chrome web browser from any computer or Android device to your TV. Load your Slideshow and cast away!
                %li If you're lucky enough to have a few iPads or Android tablets to spare, you can use DA Slideshows to turn them into digital picture frames. Open your slideshow on all of them and watch them all update at once when you change the channel!

            DA Slideshows is more fun with more screens. Figure out how to get your Slideshow onto as many screens as you can. Get creative, that's what art is all about!

        %h1 The artwork
        -# %hr
        .row
            The art channels available on DA Slideshows are drawn from the "What's Hot" page on DeviantArt. The artwork that appears on this section of DA includes much of the high-quality work that has been recently posted to DeviantArt, and refreshes quite frequently. DA Slideshows updates it's channel selection hourly, and places the newest artwork to reach the "What's Hot" page at the top of the Channels list. 