config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

Rails.application.routes.draw do

  get 'slideshows/channels'

  get 'slideshows/slideshow'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root "static_pages#home"

  devise_for :users, controllers: { registrations: "registrations" }

  match 'slideshows/update_slideshow',	to: 'slideshows#update_slideshow', 	via: 'post'
  match 'slideshows/update_slideshow',	to: 'slideshows#update_slideshow', 	via: 'get'
  match 'slideshows/', 					        to: 'static_pages#home', 			      via: 'get'
  match 'slideshows/home',              to: 'slideshows#home',              via: 'get'
  match 'slideshows/foo',               to: 'slideshows#foo',               via: 'post' 

  match '/info',                        to: 'static_pages#info',            via: 'get'

end

app/models/slideshow.rb
class Slideshow < ActiveRecord::Base

  # Validations:
  VALID_SEED_REGEX = /[A-F0-9]{8}(-[A-F0-9]{4}){3}-[A-F0-9]{12}/

  validates :seed, presence: true, length: { is: 36 }, format: VALID_SEED_REGEX, uniqueness: true

  # Relationships:
  has_and_belongs_to_many :deviations, -> { uniq }


  def results
    deviations.where(mature: false)
  end


  def nsfw
    deviations
  end

  def self.whats_hot_slideshow
    includes(:deviations).where(seed: "00000000-0000-0000-0000-000000000001").first
  end

end

app/controllers/slideshows_controller.rb
class SlideshowsController < ApplicationController

  # require 'json'
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:slideshow, :update_slideshow]


  @@wh = "00000000-0000-0000-0000-000000000001"

  # Set up data to display the channel changer.
  def channels

    @user_seed = current_user.seed

    # whats_hot = Slideshow.whats_hot_slideshow

    @channels = Slideshow.whats_hot_slideshow.results.order(created_at: :desc).map { |d| {thumb: d.thumb.sub(/https/, 'http'), uuid: d.uuid} }.compact # change .results to .nsfw for mature filter.

    # If a slideshow doesn't exist for a given seed, having it show up in the channel changer will produce errors if it's
    # selected as the user's channel. This happens when What's Hot has been updated, but before all the MLT results have been
    # retrieved for deviations new to the What's Hot list. Selecting channels only if the associated slideshow exists
    # prevents this error.
    @channels.select! { |c| Slideshow.exists?(seed: c[:uuid]) }

  end


  # Set up data to display the slideshow.
  def slideshow
    if current_user
      @user_id = current_user.uuid
    elsif params[:id]
      user = User.where(uuid: params[:id]).first
      redirect_to root_path and return unless user
      @user_id = user.uuid
    else
      redirect_to root_path and return
    end
  end



  

  # Show the logged in user's homepage. Should have links to the
  # channel changer, the slideshow, and the user profile editing
  # pages. Create a uuid unless one already exists.
  def home
    unless current_user.uuid?
      current_user.create_uuid 
      current_user.save
    end
    @uuid = current_user.uuid
  end



  # only called via AJAX. 
  def update_slideshow

    # If we get :set_uuid, we're trying to change channels on the slideshow.
    if params[:set_uuid]
      # gotta be logged in to change channels.
      render nothing: true, status: :unauthorized and return unless current_user 

      current_user.seed = params[:set_uuid]
      current_user.save
      # Add a view count to the slideshow.
      Slideshow.transaction do
        selected = Slideshow.lock("FOR SHARE").where(seed: params[:set_uuid]).first
        selected.increment!(:views)
      end

      render status: 200, json: @controller.to_json

    # If we get :current_seed, we're on the slideshow page, checking for updates.
    elsif params[:current_seed] 
      #find the user by the uuid. Will always be present so we don't neeed current_user.
      user = User.where(uuid: params[:user_id]).first
      render nothing: true, status: :expectation_failed and return unless user # Bail if no user found.
      
      seed_in_db = user.seed

      if seed_in_db == params[:current_seed]
        render json: { update: "false" } # nothing to do boat.
      else

        url_hash = { seed: seed_in_db }
        first_deviation = Deviation.where(uuid: seed_in_db).first

        url_hash[0] = { url: first_deviation.src.sub(/https/, 'http'), title: first_deviation.title, author: first_deviation.author, link: first_deviation.url } if first_deviation

        deviations = user.slideshow.results # add .where(mature: false) for mature filter.
        urls = deviations.map { |d| { url: d.src.sub(/https/, 'http'), title: d.title, author: d.author, link: d.url } }.compact

        urls.each_with_index do |u,i|
          if first_deviation
            url_hash[i+1] = u
          else
            url_hash[i] = u
          end

        end
        render json: url_hash
      end

    else
      render status: 200, json: @controller.to_json
    end

  end

end

app/helpers/slideshows_helper.rb
module SlideshowsHelper
end

app/views/slideshows/channels.html.haml
.container-fluid
    -# = link_to(image_tag("../images/back.png", height: "40px", class: "back-arrow", width: "40px"), slideshows_home_path)
    %h1 Choose a Channel!
    %span Select an image to change the channel on your slideshow at any time.
    %hr
    .torpedo-minus-wrapper
        .channel-list.torpedo.leelor
            - @channels.each do |c|
                -if c[:uuid] == @user_seed
                    .channel-selected.torpedowrap
                        = image_tag(c[:thumb], data: {uuid: c[:uuid]})
                -else    
                    .channel.torpedowrap
                        = image_tag(c[:thumb], data: {uuid: c[:uuid]})

app/views/slideshows/home.html.haml
%h1 My Account
%hr
.row
    .text-center.main-actions-container 
        = link_to("Channel Changer", slideshows_channels_path, class: "btn btn-lg btn-default main-actions")
        = link_to("My Slideshow", slideshows_slideshow_path, class: "btn btn-lg btn-default main-actions")
.row.text-center
    %p= "Direct link to slideshow: #{root_url}#{slideshows_slideshow_path.sub(/\/slideshows/,'slideshows')}?id=#{@uuid}"
    %p Use this url to display your slideshow on any device that you can't log in on, like a digital picture frame!
.row.text-center
    = link_to("Change email or password", edit_user_registration_path)
%hr        

app/views/slideshows/slideshow.html.haml
:css
    body {
        background: black;
        height: 100%;
        margin: 0;
        padding-top: 0;
    }

#back
    = link_to(image_tag("../images/back.png", id: "back-button", height: "40px", width: "40px"), slideshows_home_path)

#slideshow
    .credited
        %p.attribution-current= link_to "", "#", target: "_blank"

#placeholder
	

#current-seed
    %p Rock And Roll.

#user-id
    %p= @user_id